### ISSUE TITLE
Examples of how to use mbsync

### ISSUE THREAD

**Issue by hartmark** [jon6fingrs/mbsync-dovecot#2]
I got perfect timing for googling on how to archive mails so I can pay less for my email hosting :)

I'd love some example on how your mbsync script looks like.

**Comment by jon6fingrs** [comment]
> I got perfect timing for googling on how to archive mails so I can pay less for my email hosting :)
> 
> 
> 
> I'd love some example on how your mbsync script looks like.

Do you mean to set mbsync to automatically fetch mails?

**Comment by hartmark** [comment]
Yes

`Once you make the mbsync container, you need a cron job or something so that it'll autorun every X minutes (I have mine run every 5 minutes)`

This is the one I was wondering about

**Comment by jon6fingrs** [comment]
Sure sorry. I added the example from my mbsync repo to this readme. Let me know if there are any issues.

**Comment by hartmark** [comment]
Cool, I don't know if I have any time this weekend, but I'll report back if I have any problems

**Comment by Leopere** [comment]
I've included my swarm stack example if anyone wants it with a restart set to once every hour.
```yaml
  mbsync:
    image: thehelpfulidiot/mbsync:latest
#    container_name: mbsync
    volumes:
      - /mnt/tank/persist/nixc.us/mbsync/production/dovecot:/mail # same as dovecot
    environment:
      - host_name=imap.gmail.com
      - port=993
      - remote_username=example@gmail.com
      - remote_password=redacted
      - ssltype=IMAPS
      - sslversions=TLSv1.2
      - mailbox_name=gmail
      - PUID=1000
    deploy:
      replicas: 1
      restart_policy:
        delay: 1h
    networks:
      - default
```
