### ISSUE TITLE
Where do I set username and password for the dovecot container for my web client to log into?

### ISSUE THREAD

**Issue by Leopere** [jon6fingrs/mbsync-dovecot#3]
https://github.com/jon6fingrs/mbsync-dovecot/blob/main/README.md#dovecot
the env vars for Dovecot for credentials are for my mail client connection?

**Comment by Leopere** [comment]
Fixed my horrible issue title.

**Comment by jon6fingrs** [comment]
> Fixed my horrible issue title.
> 
> 

The dovecot credentials are the credentials you are creating for the local imap server. Set them to whatever you want and use those from your local clients.

**Comment by Leopere** [comment]
Thank you for clearing that up I wasn't certain if these credentials were just for the far server. 

I was having trouble logging in with them in my testing. I'm sure I'm the point of failure here.

**Comment by Leopere** [comment]
I've been trying to use RainLoop for accessing this Dovecot instance using this configuration essentially.

```yaml
  webmail:
    image: hardware/rainloop
    restart: always
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.mbsync.tls=true"
        - "traefik.http.services.mbsync.loadbalancer.server.port=8888"
        - "traefik.http.routers.mbsync.rule=Host(`mbsync.example.com`)"
        - "traefik.http.routers.mbsync.entrypoints=websecure"
        - "traefik.http.routers.mbsync.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.mbsync.service=mbsync"
        - "traefik.docker.network=traefik"
    labels:
      - "traefik.backend=mbsync"
      - "traefik.enable=true"
      - "traefik.port=8888"
      - "traefik.frontend.rule=Host:mbsync.example.com"
      - "traefik.docker.network=traefik"
    volumes:
      - /mnt/tank/persist/example.com/mbsync/production/data:/rainloop/data
    networks:
      - traefik
```

However, it seems RainLoop refuses only to have IMAP configured is there a recommended client you suggest using for accessing the mbsync data?
